// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-cascader-1": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-1.tsx"),
  "c-cascader-2": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-2.tsx"),
  "c-cascader-3": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-3.tsx"),
  "c-cascader-4": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-4.tsx"),
  "c-cascader-5": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-5.tsx"),
  "c-cascader-6": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-6.tsx"),
  "c-cascader-7": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-7.tsx"),
  "c-cascader-8": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-8.tsx"),
  "c-cascader-9": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-9.tsx"),
  "c-cascader-10": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-10.tsx"),
  "c-cascader-11": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-11.tsx"),
  "c-cascader-12": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-12.tsx"),
  "c-cascader-13": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-13.tsx"),
  "c-cascader-14": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-14.tsx"),
  "c-cascader-15": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-15.tsx"),
  "c-cascader-16": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-16.tsx"),
  "c-cascader-17": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-17.tsx"),
  "c-cascader-18": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-18.tsx"),
  "c-cascader-19": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-19.tsx"),
  "c-cascader-20": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-20.tsx"),
  "c-cascader-21": () => import("@/registry-reui/bases/radix/components/cascader/c-cascader-21.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
