// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-bubble-1": () => import("@/registry-reui/bases/radix/components/bubble/c-bubble-1.tsx"),
  "c-bubble-2": () => import("@/registry-reui/bases/radix/components/bubble/c-bubble-2.tsx"),
  "c-bubble-3": () => import("@/registry-reui/bases/radix/components/bubble/c-bubble-3.tsx"),
  "c-bubble-4": () => import("@/registry-reui/bases/radix/components/bubble/c-bubble-4.tsx"),
  "c-bubble-5": () => import("@/registry-reui/bases/radix/components/bubble/c-bubble-5.tsx"),
  "c-bubble-6": () => import("@/registry-reui/bases/radix/components/bubble/c-bubble-6.tsx"),
  "c-bubble-7": () => import("@/registry-reui/bases/radix/components/bubble/c-bubble-7.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
