// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-time-picker-1": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-1.tsx"),
  "c-time-picker-2": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-2.tsx"),
  "c-time-picker-3": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-3.tsx"),
  "c-time-picker-4": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-4.tsx"),
  "c-time-picker-5": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-5.tsx"),
  "c-time-picker-6": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-6.tsx"),
  "c-time-picker-7": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-7.tsx"),
  "c-time-picker-8": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-8.tsx"),
  "c-time-picker-9": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-9.tsx"),
  "c-time-picker-10": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-10.tsx"),
  "c-time-picker-11": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-11.tsx"),
  "c-time-picker-12": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-12.tsx"),
  "c-time-picker-13": () => import("@/registry-reui/bases/radix/components/time-picker/c-time-picker-13.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
