// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-marker-1": () => import("@/registry-reui/bases/radix/components/marker/c-marker-1.tsx"),
  "c-marker-2": () => import("@/registry-reui/bases/radix/components/marker/c-marker-2.tsx"),
  "c-marker-3": () => import("@/registry-reui/bases/radix/components/marker/c-marker-3.tsx"),
  "c-marker-4": () => import("@/registry-reui/bases/radix/components/marker/c-marker-4.tsx"),
  "c-marker-5": () => import("@/registry-reui/bases/radix/components/marker/c-marker-5.tsx"),
  "c-marker-6": () => import("@/registry-reui/bases/radix/components/marker/c-marker-6.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
