// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-signature-pad-1": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-1.tsx"),
  "c-signature-pad-2": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-2.tsx"),
  "c-signature-pad-3": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-3.tsx"),
  "c-signature-pad-4": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-4.tsx"),
  "c-signature-pad-5": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-5.tsx"),
  "c-signature-pad-6": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-6.tsx"),
  "c-signature-pad-7": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-7.tsx"),
  "c-signature-pad-8": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-8.tsx"),
  "c-signature-pad-9": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-9.tsx"),
  "c-signature-pad-10": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-10.tsx"),
  "c-signature-pad-11": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-11.tsx"),
  "c-signature-pad-12": () => import("@/registry-reui/bases/base/components/signature-pad/c-signature-pad-12.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
