// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-message-1": () => import("@/registry-reui/bases/base/components/message/c-message-1.tsx"),
  "c-message-2": () => import("@/registry-reui/bases/base/components/message/c-message-2.tsx"),
  "c-message-3": () => import("@/registry-reui/bases/base/components/message/c-message-3.tsx"),
  "c-message-4": () => import("@/registry-reui/bases/base/components/message/c-message-4.tsx"),
  "c-message-5": () => import("@/registry-reui/bases/base/components/message/c-message-5.tsx"),
  "c-message-6": () => import("@/registry-reui/bases/base/components/message/c-message-6.tsx"),
  "c-message-7": () => import("@/registry-reui/bases/base/components/message/c-message-7.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
